<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Bower JSON</string>
	<key>fileTypes</key>
	<array>
		<string>bower.json</string>
		<string>.bowerrc</string>
	</array>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.json</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.json, source.json.bower</string>
</dict>
</plist>
