<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Dockerfile</string>
	<key>fileTypes</key>
	<array>
		<string>Dockerfile</string>
	</array>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.shell</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.shell, source.dockerfile</string>
</dict>
</plist>
