"light": {
  "folderExpanded": "_folder_open",
  "folder": "_folder_light",
  "rootFolder": "_folder_root_light",
  "rootFolderExpanded": "_folder_root_open",
  "folderNames": {
    "test": "_folder_test",
    "node_modules": "_folder_node",
    "assets": "_folder_assets",
    "bower_components": "_folder_bower",
    "js": "_folder_js",
    "src": "_folder_src",
    "images": "_folder_images",
    ".git": "_folder_git",
    ".github": "_folder_github",
    ".vscode": "_folder_vscode",
    ".gulp": "_folder_gulp",
    "build": "_folder_dark_build",
    "dist": "_folder_dist"
  },
  "folderNamesExpanded": {
    "test": "_folder_test_open",
    "node_modules": "_folder_node_open",
    "bower_components": "_folder_bower_open",
    "assets": "_folder_assets_open",
    "src": "_folder_src_open",
    "images": "_folder_images_open",
    "js": "_folder_js_open",
    ".git": "_folder_git_open",
    ".github": "_folder_github_open",
    ".gulp": "_folder_gulp_open",
    ".vscode": "_folder_vscode_open",
    "build": "_folder_open_build",
    "dist": "_folder_dist_open"
  }
},
